name: Check ESLint and Format

on:
  push:
    paths:
      - 'src/**'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: yarn

      - name: Check ESLint
        run: yarn lint

      - name: Check Format
        run: yarn format
